### ISSUE TITLE
Argonite Transformers and Oil Extractors failing to properly spawn their Sub-Entities

### ISSUE THREAD

**Issue by ArsiTheFox** [Metastruct/mining#4]
When the Argonite Transformer hits 100% it attempts to spawn a battery but then immediately removes it. same for Oil Extractor
![gmod_GFMR6p1rB2](https://github.com/Metastruct/mining/assets/24835664/11954ebc-e9a2-4b88-9092-546563a1e55c)
A Gif showing the issue as well: https://puu.sh/JScvn.gif

**Comment by Earu** [comment]
Is this even relevant anymore?

**Comment by Earu** [comment]
Closing, stale.
